import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>E-commerce</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <nav>
        <Navbar />
      </nav>
      <main>
        
      </main>

      <footer>
        <Footer />
      </footer>
    </>
  )
}
